name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  [push,pull_request]

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["latest"]
        ghc: ["8.10.4"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'
      
    - uses: actions/cache@v2.1.3
      name: Cache Stack Artifacts
      with:
        path: |
          ~/.stack
          ~/.local/bin
          .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack-6

    - name: Install non-Haskell dependencies
      run: sudo apt-get install libgtk-3-dev gobject-introspection libgirepository1.0-dev libwebkit2gtk-4.0-dev libgtksourceview-3.0-dev
      
    - uses: haskell/actions/setup@v1
      id: setup-haskell-stack
      name: Setup Stack
      with:
        enable-stack: true
        stack-setup-ghc: true
        stack-no-global: true
    
    - name: Install dependencies
      run: |
        stack --stack-yaml=stack.yaml install --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
    - name: Build
      run: |
        stack --stack-yaml=stack.yaml build --test --bench --no-run-tests --no-run-benchmarks
    - name: Test
      run: |
        stack --stack-yaml=stack.yaml test
